### ISSUE TITLE
Can't open index.html

### ISSUE THREAD

**Issue by ryanNewcodeer123** [flowforfrank/mario#1]
Hi, I am new to js and I just wanted to start a new project, and I found this on [webtips. dev](https://www.webtips.dev/webtips/phaser/remake-mario-in-phaserjs-part1) and I just copied your index.html to my and type npx parcel index.html but it shows this: 
![Screenshot 2022-09-03 184055](https://user-images.githubusercontent.com/110335999/188282548-1d979b01-2aa9-4bec-85ab-ca32d8db74cd.png)
![Screenshot 2022-09-03 184748](https://user-images.githubusercontent.com/110335999/188282552-7ec3e09c-af74-42c7-99b2-06a06e5e2a6a.png)
My index.js:
![Screenshot 2022-09-03 184434](https://user-images.githubusercontent.com/110335999/188282582-8fe54a5e-c061-40e1-9558-3530ca3bb234.png)
How to fix that? 
Also, my package.json and package-lock.json is also coped from you
Let me know how to fix that.
Many thanks
Ryan

**Comment by flowforfrank** [comment]
Hey @ryanNewcodeer123 
After cloning the GitHub repo, you need to run `npm i` to install all dependencies. The reason you are getting the errors is because you have not installed the dependencies and so NPM cannot find Phaser or Parcel. After the installation is done, you can run `npm run start` to start the project, so in order, you need to do the following inside your terminal:

```
- npm i
- npm run start
```
